### ISSUE TITLE
k-space off center and zero values

### ISSUE THREAD

**Issue by Phillistan16** [mylyu/M4Raw#2]
Hi Dr. Lyu and Team,

Thank you for your efforts in releasing this valuable dataset. 

I loaded the dataset with the suggested approach from M4Raw_tutorial.ipynb, and noticed the k-space center (location with largest absolute value) does not lie on the center of the matrix [128,128]. Instead, for T1 images they consistently appear near [136, 128], and for T2 and FLAIR images they appear near [125,128]. In addition, some k-space values within the readout were zero. Attached is a visualization of the log(abs(kspace)), note that zero values also appear white because they equal to -Inf. 

I'm wondering if these were on purpose or if I loaded the dataset incorrectly. I appreciate your time looking into this! 

![Figure 2023-11-01 145628](https://github.com/mylyu/M4Raw/assets/22829346/f3a29487-8407-45e5-8daf-33bb92d61cd7)

**Comment by mylyu** [comment]
Hi,
You are right about the k-space being off-center. It was likely because of sequence-related hardware timing problem. This should have little impact on most applications, and you can correct them manually if needed. But I don't think our data have any zeros within the readout. What you saw is likely because you used the np.log function without adding a small number like 
`np.log(np.abs(slice_kspace) + 1e-9)`.

**Comment by mylyu** [comment]
Hi,

You are right about the k-space being off-center. It was likely because of sequence-related hardware timing problem. This should have little impact on most applications, and you can correct them manually if needed. 

When you look at k-space of a single-coil, some values may be very small and have been rounded to zeros by the scanner. This wouldn't be happening if you first sum along the coil dimension. I suggest using np.log(np.abs(slice_kspace) + 1e-2) to visualize single-coil k-space.

**Comment by mylyu** [comment]
I just confirmed with the scanner vendor. The k-space sometimes has zeros because the spectrometer was designed long time ago that it rounds small values to zeros. This should not cause noticeable problem usually, but one should be carefully when writing reconstruction code.
